export const LOADING = "LOADING";
export const ERROR = "ERROR";

// app setting
export const SHOW_CONNECTION_DIALOG = "SHOW_CONNECTION_DIALOG";
export const HIDE_CONNECTION_DIALOG = "HIDE_CONNECTION_DIALOG";
export const ACTIVE_CONNECTION = "ACTIVE_CONNECTION";

// Connections
export const ADD_CONNECTION = "ADD_CONNECTION";
export const EDIT_CONNECTION = "EDIT_CONNECTION";
export const DELETE_CONNECTION = "DELETE_CONNECTION";

// Databases
export const FETCHING_DATABASE = "FETCHING_DATABASE";
export const FETCHING_DATABASE_SUCCESS = "FETCHING_DATABASE_SUCCESS";
export const FETCHING_DATABASE_ERROR = "FETCHING_DATABASE_ERROR";

// Tables
export const FETCHING_TABLES = "FETCHING_TABLES";
export const FETCHING_TABLES_SUCCESS = "FETCHING_TABLES_SUCCESS";
export const FETCHING_TABLES_ERROR = "FETCHING_TABLES_ERROR";
